# Generated by Django 5.1.1 on 2024-12-10 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_name', models.CharField(max_length=50)),
                ('blind_price', models.FloatField(default=0)),
                ('blind_quantity', models.FloatField(default=0)),
                ('blind_length', models.FloatField(default=0)),
                ('blind_width', models.FloatField(default=0)),
                ('square_foot', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('total_blind_count', models.FloatField(default=0)),
                ('sold_blinds', models.FloatField(default=0)),
                ('pending_order', models.FloatField(default=0)),
                ('blind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.blind')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blind',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
