# Generated by Django 5.1.1 on 2025-01-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='purchased_blind',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='blind',
            name='remaining_quantity',
            field=models.FloatField(default=0),
        ),
    ]
