# Generated by Django 5.1.1 on 2025-01-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_balance_purchased_blind_blind_remaining_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='purchased_blind',
        ),
        migrations.AddField(
            model_name='blind',
            name='purchased_blind',
            field=models.FloatField(default=0),
        ),
    ]
