# Generated by Django 5.1.1 on 2025-01-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_transaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
