# Generated by Django 5.1.1 on 2025-01-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blind',
            name='client',
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
