# Generated by Django 5.1.1 on 2025-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_blind_client_transaction_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Payment Pending'), ('Paid', 'Payment Done')], default='Pending', max_length=10),
        ),
    ]
