# Generated by Django 5.1.1 on 2025-01-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_transaction_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_group_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
