# Generated by Django 5.1.1 on 2025-01-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_transaction_transaction_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_group_id',
        ),
    ]
