# Generated by Django 5.1.1 on 2025-01-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_transaction_transaction_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
