# Generated by Django 5.1.1 on 2025-01-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_transaction_transaction_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
    ]
