# Generated by Django 5.1.1 on 2025-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_transaction_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='blind',
            name='blind_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
