# Generated by Django 5.1.1 on 2025-02-08 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_blind_blind_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
