# Generated by Django 5.1.1 on 2025-02-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_transaction_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='group_id',
        ),
    ]
