# Generated by Django 5.1.1 on 2025-02-08 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_transaction_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
