# Generated by Django 5.1.1 on 2025-02-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_transaction_transaction_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_group',
        ),
    ]
