# Generated by Django 4.2.7 on 2025-03-04 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_transaction_transaction_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='blind_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='blind_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='length',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='square_foot',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='width',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blind',
            name='blind_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('square_foot', models.FloatField()),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('blind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.blind')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.transaction')),
            ],
        ),
    ]
