# Generated by Django 5.1.1 on 2025-03-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_transactionitem_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiving_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remaining_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_balance',
            field=models.FloatField(default=0),
        ),
    ]
